<a href="https://colab.research.google.com/github/Deekshavij13/Deekshavij13/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np
print("Numpy version:", np.__version__)
np.show_config()


Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
import numpy as np
null_vector = np.zeros(10)

print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
import numpy as np
array = np.zeros(10)
memory_size = array.nbytes

print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
import numpy as np
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
import numpy as np
vector = np.zeros(10)
vector[4] = 1

print(vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import numpy as np
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
import numpy as np
vector = np.arange(10, 50)
reversed_vector = vector[::-1]

print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)[0]

print(indices)


[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
import numpy as np
identity_matrix = np.eye(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
import numpy as np
random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.19480085 0.40730295 0.87667743]
  [0.10185906 0.69815486 0.18568774]
  [0.65547899 0.46552298 0.33044285]]

 [[0.33682449 0.19148027 0.86257892]
  [0.38220526 0.68086016 0.18184668]
  [0.67448121 0.25703748 0.21999129]]

 [[0.60016718 0.4122045  0.17572378]
  [0.00604264 0.60911735 0.62568529]
  [0.8892331  0.89314342 0.86229486]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
import numpy as np
random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.64025299 0.54021748 0.76689955]
  [0.60304713 0.53560812 0.18139159]
  [0.79325902 0.98360976 0.69156427]]

 [[0.73209978 0.26742778 0.8883925 ]
  [0.05847836 0.96061697 0.63952138]
  [0.31912008 0.0855553  0.46500898]]

 [[0.23841857 0.19396966 0.68528623]
  [0.77388034 0.72817584 0.08063857]
  [0.26631386 0.68848158 0.32444945]]]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Array:")
print(random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)


Array:
[[0.59426043 0.1136573  0.44762211 0.99640295 0.19483987 0.2417955
  0.72197997 0.56620953 0.71841859 0.64499362]
 [0.49757397 0.95143608 0.65610432 0.59865722 0.368076   0.99436081
  0.06527181 0.17233437 0.70086649 0.65722338]
 [0.48452727 0.49029815 0.86845332 0.3947103  0.0077201  0.29407602
  0.44981174 0.63788608 0.4157991  0.66827931]
 [0.99927308 0.35444872 0.85745617 0.60898709 0.13825558 0.10684043
  0.15937923 0.16706108 0.69166583 0.21927407]
 [0.64188641 0.43651086 0.51633016 0.12711592 0.10124745 0.28879998
  0.14248691 0.432504   0.32804594 0.80760107]
 [0.0613379  0.20650555 0.73257832 0.02824713 0.54703976 0.13872757
  0.99796436 0.00676998 0.24773012 0.82062007]
 [0.01553117 0.69885798 0.00131906 0.45051161 0.5581822  0.78914395
  0.36386397 0.87229312 0.33006149 0.0322711 ]
 [0.56107811 0.14272726 0.89451354 0.8796881  0.05877403 0.00460134
  0.89421029 0.03804236 0.83468965 0.64636906]
 [0.78821711 0.45490695 0.09252411 0.45125657 0.59063861 0.58346357
  0.53

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
import numpy as np
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)

print("Random Vector:")
print(random_vector)
print("\nMean Value:", mean_value)


Random Vector:
[0.79894457 0.76239646 0.6305391  0.97242069 0.12270203 0.24709841
 0.57919281 0.17805072 0.67896337 0.56292835 0.99440622 0.35460862
 0.00538579 0.76117918 0.07003473 0.74632195 0.76500628 0.08233802
 0.09194074 0.83558457 0.68991554 0.90908236 0.86973009 0.03972114
 0.67041227 0.35534674 0.94864045 0.79904605 0.51782394 0.41107973]

Mean Value: 0.5483613632801803


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array_with_border)


[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan → np.nan
np.nan == np.nan → False
np.inf > np.nan → False
np.nan - np.nan → np.nan
np.nan in set([np.nan]) → True
0.3 == 3 * 0.1 → False

SyntaxError: invalid character '→' (U+2192) (<ipython-input-18-cca5be070996>, line 1)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
import numpy as np
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])

print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
n = 100
z = n % 8
y = (n // 8) % 7
x = n // (8 * 7)

print(x, y, z)


1 5 4


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
import numpy as np
checkerboard_pattern = np.array([[1, 0], [0, 1]])
checkerboard = np.tile(checkerboard_pattern, (4, 4))

print(checkerboard)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
import numpy as np
matrix = np.random.random((5, 5))
min_val = matrix.min()
max_val = matrix.max()
normalized_matrix = (matrix - min_val) / (max_val - min_val)

print("Original Matrix:")
print(matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.26077477 0.17434364 0.41156601 0.28316844 0.43983485]
 [0.87514008 0.75172849 0.65538488 0.67368572 0.52309741]
 [0.5778013  0.77545036 0.04013847 0.89652305 0.84521586]
 [0.81451934 0.50420336 0.46344275 0.44018571 0.12888504]
 [0.00558611 0.17972779 0.05791744 0.10400834 0.75463145]]

Normalized Matrix:
[[0.28642729 0.1894158  0.45567748 0.31156227 0.48740681]
 [0.97599945 0.83748057 0.72934317 0.74988428 0.58086187]
 [0.64226228 0.86410633 0.03878204 1.         0.9424121 ]
 [0.9079579  0.55965493 0.51390465 0.48780063 0.13839243]
 [0.         0.19545904 0.05873741 0.11047048 0.8407389 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
import numpy as np
rgba_dtype = np.dtype([('r', np.uint8),
                       ('g', np.uint8),
                       ('b', np.uint8),
                       ('a', np.uint8)])
colors = np.array([(255, 0, 0, 255),
                   (0, 255, 0, 255),
                   (0, 0, 255, 255),
                   (255, 255, 0, 255)],
                  dtype=rgba_dtype)

print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
import numpy as np
A = np.random.random((5, 3))
B = np.random.random((3, 2))
C = np.dot(A, B)

print("Matrix A (5x3):")
print(A)

print("\nMatrix B (3x2):")
print(B)

print("\nMatrix C (Result of A * B):")
print(C)


Matrix A (5x3):
[[0.98037566 0.01347039 0.33211107]
 [0.08867453 0.39404901 0.71469262]
 [0.93809661 0.17860858 0.98446161]
 [0.12815593 0.21769426 0.99833697]
 [0.39933656 0.8393966  0.96529831]]

Matrix B (3x2):
[[0.61345094 0.0088518 ]
 [0.59403103 0.68787015]
 [0.93340032 0.84917644]]

Matrix C (Result of A * B):
[[0.91940678 0.29996487]
 [0.95556913 0.87873962]
 [1.60047207 0.96714497]
 [1.13978257 0.99864403]
 [1.64461077 1.40063929]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [30]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = (arr > 3) & (arr < 8)
arr[mask] = -arr[mask]

print("Modified array:")
print(arr)



Modified array:
[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:


print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [33]:
Z**Z
2 << Z >> 2
1j*Z
Z/1/1


NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)